---
- name: Create ansible-playbook-access Namespace
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ocp_service_account_namespace }}"

- name: Create ServiceAccount
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ ocp_service_account_name }}"
        namespace: "{{ ocp_service_account_namespace }}"

- name: Create temporary directory for template files
  tempfile:
    state: directory
    suffix: tmp
  register: tmp_dir

- set_fact:
    working_dir: "{{ tmp_dir.path }}"

- name: Populate Templates
  template:
    src: "{{ item }}"
    dest: "{{ working_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - ./templates/*.j2

- name: Apply Templates
  k8s:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    src: "{{ item }}"
    state: "{{ state }}"
    api_version: v1
  with_fileglob:
    - "{{ working_dir }}/*.yaml"

- name: Get ServiceAccount Secret
  k8s_info:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    kind: Secret
    namespace: "{{ ocp_service_account_namespace }}"
  register: sa_secrets
  when: state == "present"

- name: Get Service Account token
  set_fact:
    sa_token: "{{ item.data.token | b64decode }}"
  with_items: "{{ sa_secrets.resources }}"
  when: (state == "present") and
        (item.metadata.name.startswith(ocp_service_account_name + "-token-"))
  loop_control:
    label: "{{ item.metadata.name }}"

- name: Encrypt token
  command: ansible-vault encrypt_string --vault-password-file ~/.passfile '{{ sa_token }}' --name '{{ ocp_token_var }}'
  register: encrypted_var
  when: state == "present"

- name: Create encrypted token file
  copy:
    dest: "{{ ocp_service_account_tokenfile }}"
    content: "{{ encrypted_var.stdout }}"
  when: state == "present"

- name: Remove token file
  file:
    path: "{{ ocp_service_account_tokenfile }}"
    state: absent
  when: state == "absent"

...